/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// It's included here so the project has valid TypeScript types even
// before Vercel's first build runs. Do not edit this file manually.
